In [52]:
import numpy as np

In [53]:
a1 = np.array([1,2,3,4,5,6]) #simple array
print(a1) # print an array

[1 2 3 4 5 6]


In [54]:
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]]) #2 Dimensional array
print(a2) # Print an 2D array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [55]:
print("Shape of a1{}".format(a1.shape)) # Return shape of an array

Shape of a1(6,)


In [56]:
print("Shape of a2{}".format(a2.shape)) # Return shape of an 2D array

Shape of a2(2, 5)


In [57]:
a = np.array([1,2,3,4,5,6,7,8])

In [58]:
print("size {}".format(a1.size)) # Print size of an array
print(f"dtype {a1.dtype}") # print data type of an array
print(f"itemsize {a1.itemsize}") # print itemsize of an array
print(f"data {a1.data}")


size 6
dtype int64
itemsize 8
data <memory at 0x7f6b7694e400>


In [59]:
print(a[1:4]) #print slicing of an array

[2 3 4]


In [60]:
a = np.array([1,2,3,4,5,6,7,8])
print(a[1:4])

[2 3 4]


In [61]:
n1 = np.array([[1,2],[3,4]])
n2 = np.array([[5,6],[7,8]])
print(n1)
print(n2)
mul=np.dot(n1,n2) # Calculate the dot element of 'a' and 'b'
print(mul) # print the result of an dot element


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [62]:
mulM= np.multiply(n1,n2) # Multiplication of an array
print(mulM)

[[ 5 12]
 [21 32]]


In [63]:
add1= np.add(n1,n2) # Addition of an array
print(add1)

[[ 6  8]
 [10 12]]


In [64]:
subtract1= np.subtract(n2,n1 # Subtraction of an array
print(subtract1)

[[4 4]
 [4 4]]


In [65]:
divide1 = np.divide(n1,n2) # Division of an array
print(divide1)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [66]:
m3 = np.array([1,2,3,4,5,6,7,8,9])
print(m3)
re = m3.reshape(3,3)
print(re) # Reshape an array

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
print("Maximum number is : ",m3.max()) # Give maximum number from an array
print("Minimum number is : ",m3.min()) # Give minimum number from an array
print("Maximum number is : ",re.max(axis=1)) # Give maximum number from rows of an matrix 
print("Minimum number is : ",re.min(axis=0)) # Give minimum number from columns of an matrix

Maximum number is :  9
Minimum number is :  1
Maximum number is :  [3 6 9]
Minimum number is :  [1 2 3]


In [68]:
m4 = np.array([[4,9,25],[36,49,64]])
print(m4)
print(np.sqrt(m4)) # Give square root of an elements from array
print(np.std(m4)) # Give standard deviation of an elements from array 

[[ 4  9 25]
 [36 49 64]]
[[2. 3. 5.]
 [6. 7. 8.]]
21.16141667175323


In [69]:
v = np.vstack((n1,n2)) # Give vertical stack of an array
print(v)
h = np.hstack((n1,n2)) # Give horizontal stack of an array
print(h)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [71]:
arr = np.arange(0,20,2,float) # Return range of an element from 0 to 20 in float data type 
print(arr)
print("Data Type : ", arr.dtype)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
Data Type :  float64


In [72]:
arr1 = np.linspace(0,20,3) # Create 3 evenly spaced number from 0 to 20 
print(arr1)

[ 0. 10. 20.]


In [77]:
ht = h.T # Transpose array 'h'
print(ht) #Print the Transpose array

[1 2 3 4]


In [78]:
vt = v.T 
print(vt) 

[[1 3]
 [2 4]]


In [79]:
for i in np.nditer(ht):
    print("Ak",i) #  iterating over elements of an array

Ak 1
Ak 2
Ak 3
Ak 4


In [80]:
print(np.exp(n1)) # compute the exponential of all elements of an array

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


In [82]:
print(np.sin(n1)) # computes the sine of each element of an array

[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]


In [81]:
print(np.cos(n1)) # computes the cosine of each element of an array

[[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]


In [83]:
print(np.log(n1)) # computes the natural logarithm of each element an array

[[0.         0.69314718]
 [1.09861229 1.38629436]]


In [84]:
print(np.sum(n1)) # Calculate total element of an array

10


In [85]:
from scipy import stats as st
print('mean',np.mean(n1)) # Print mean of an array

mean 2.5


In [86]:
print('median',np.median(n1)) # Print median of an array

median 2.5


In [88]:
print('mode',st.mode(n1)) # Print mode of an array

mode ModeResult(mode=array([[1, 2]]), count=array([[1, 1]]))
